### ISSUE TITLE
about render on server

### ISSUE THREAD

**Issue by LogWell** [SiriusFuenmayor/datasciencecoursera#1]
Hello, sorry to bother you.

I just need to render mesh data on the server.

How do you do it?

THANKS!!!

**Comment by SiriusFuenmayor** [comment]
What mesh on what server?

**Comment by LogWell** [comment]
`*.obj` on `Ubuntu 16.04.6 LTS` server

**Comment by SiriusFuenmayor** [comment]
ok NaGenHao follow the instructions in this pages

https://joshh.info/2016/xserver-inside-docker-container/

https://github.com/mviereck/x11docker

http://fabiorehm.com/blog/2014/09/11/running-gui-apps-with-docker/
